blank_issues_enabled: false
contact_links:
  - name: ğŸ™‹ Ask a question
    url: https://github.com/polybar/polybar/blob/master/SUPPORT.md
    about: Have a look at our support resources and channels
  - name: ğŸ’¡ Feature request
    url: https://github.com/polybar/polybar/discussions/categories/ideas
    about: Suggest your idea over in Discussions
  - name: ğŸ› ï¸ Build Issues
    url: https://github.com/polybar/polybar/discussions/categories/build-support
    about: Get support when building polybar from source
